# Generated by Django 5.0.6 on 2026-05-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCostume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('epoque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=50)),
                ('taille', models.CharField(max_length=10)),
                ('etat', models.CharField(choices=[('Neuf', 'Neuf'), ('Bon état', 'Bon état'), ('À réparer', 'À réparer'), ('Usé', 'Usé')], max_length=20)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acteurs.acteur')),
                ('type_costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumes.typecostume')),
            ],
        ),
    ]
